// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: applications/protobuf/calculator.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_applications_protobuf_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_applications_protobuf_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_applications_protobuf_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Operators struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float32                `protobuf:"fixed32,1,opt,name=a,proto3" json:"a,omitempty"`
	B             float32                `protobuf:"fixed32,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operators) Reset() {
	*x = Operators{}
	mi := &file_applications_protobuf_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operators) ProtoMessage() {}

func (x *Operators) ProtoReflect() protoreflect.Message {
	mi := &file_applications_protobuf_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operators.ProtoReflect.Descriptor instead.
func (*Operators) Descriptor() ([]byte, []int) {
	return file_applications_protobuf_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *Operators) GetA() float32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Operators) GetB() float32 {
	if x != nil {
		return x.B
	}
	return 0
}

var File_applications_protobuf_calculator_proto protoreflect.FileDescriptor

const file_applications_protobuf_calculator_proto_rawDesc = "" +
	"\n" +
	"&applications/protobuf/calculator.proto\x12\x05proto\"\x1b\n" +
	"\x03msg\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"'\n" +
	"\toperators\x12\f\n" +
	"\x01a\x18\x01 \x01(\x02R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x02R\x01b2\xd0\x01\n" +
	"\x11arithmeticService\x12+\n" +
	"\vGetAddition\x12\x10.proto.operators\x1a\n" +
	".proto.msg\x12.\n" +
	"\x0eGetSubtraction\x12\x10.proto.operators\x1a\n" +
	".proto.msg\x121\n" +
	"\x11GetMultiplication\x12\x10.proto.operators\x1a\n" +
	".proto.msg\x12+\n" +
	"\vGetDivision\x12\x10.proto.operators\x1a\n" +
	".proto.msgB\x17Z\x15applications/protobufb\x06proto3"

var (
	file_applications_protobuf_calculator_proto_rawDescOnce sync.Once
	file_applications_protobuf_calculator_proto_rawDescData []byte
)

func file_applications_protobuf_calculator_proto_rawDescGZIP() []byte {
	file_applications_protobuf_calculator_proto_rawDescOnce.Do(func() {
		file_applications_protobuf_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_applications_protobuf_calculator_proto_rawDesc), len(file_applications_protobuf_calculator_proto_rawDesc)))
	})
	return file_applications_protobuf_calculator_proto_rawDescData
}

var file_applications_protobuf_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_applications_protobuf_calculator_proto_goTypes = []any{
	(*Msg)(nil),       // 0: proto.msg
	(*Operators)(nil), // 1: proto.operators
}
var file_applications_protobuf_calculator_proto_depIdxs = []int32{
	1, // 0: proto.arithmeticService.GetAddition:input_type -> proto.operators
	1, // 1: proto.arithmeticService.GetSubtraction:input_type -> proto.operators
	1, // 2: proto.arithmeticService.GetMultiplication:input_type -> proto.operators
	1, // 3: proto.arithmeticService.GetDivision:input_type -> proto.operators
	0, // 4: proto.arithmeticService.GetAddition:output_type -> proto.msg
	0, // 5: proto.arithmeticService.GetSubtraction:output_type -> proto.msg
	0, // 6: proto.arithmeticService.GetMultiplication:output_type -> proto.msg
	0, // 7: proto.arithmeticService.GetDivision:output_type -> proto.msg
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_applications_protobuf_calculator_proto_init() }
func file_applications_protobuf_calculator_proto_init() {
	if File_applications_protobuf_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_applications_protobuf_calculator_proto_rawDesc), len(file_applications_protobuf_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_applications_protobuf_calculator_proto_goTypes,
		DependencyIndexes: file_applications_protobuf_calculator_proto_depIdxs,
		MessageInfos:      file_applications_protobuf_calculator_proto_msgTypes,
	}.Build()
	File_applications_protobuf_calculator_proto = out.File
	file_applications_protobuf_calculator_proto_goTypes = nil
	file_applications_protobuf_calculator_proto_depIdxs = nil
}
